### ISSUE TITLE
Integrate dynamically created k8s cluster with vault

### ISSUE THREAD

**Issue by artem-v** [scalecube/spinless#18]
## Subtasks:
When create k8s cluster provision vault access into this new cluster: 
```
provisionVault(cluster_name) 
  mountKub8sAuthVaultMethod(cluster_name)
  createKub8sVaultServiceAccount(cluster_name)
```

- [x] `mountKub8sAuthVaultMethod(cluster_name)`:
`$ vault auth enable --path="$cluster_name" kubernetes`

- [ ]  `createKub8sVaultServiceAccount(cluster_name)`:
* create service account for vault -to- kub8s integration:
```
$ cat <<EOF | kubectl create -f -
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
EOF
```

* Collect parameters `TOKEN_REVIEW_JWT`, `KUBE_CA_CERT`, `KUBE_HOST` and execute `vault write auth/$cluster_name/config`:
```
$ TOKEN_REVIEW_JWT=$(kubectl get secret vault-auth -o go-template='{{ .data.token }}' | base64 --decode)
$ KUBE_CA_CERT=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)
$ KUBE_HOST=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.server}')
$ vault write auth/$cluster_name/config \
    token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
    kubernetes_host="$KUBE_HOST" \
    kubernetes_ca_cert="$KUBE_CA_CERT"
```

- [ ] Update `create_role` function, pass cluster name as a paramete and use it as a `mount_point` which is now hardcoded to `"kubernetes"`: 
```
    def create_role(self):
        self.logger.info("Creating service role")
        policy_name = self.create_policy()
        try:
            self.__auth_client()
            self.client.create_role("{}-role".format(self.app_path),
                                    mount_point="kubernetes", <<-- CHANGE ME on $cluster_name
                                    bound_service_account_names="{}".format(self.app_path),
                                    bound_service_account_namespaces="*",
                                    policies=[policy_name], ttl="1h")
        except Exception as e:
            self.logger.info("Vault create_role exception is: {}".format(e))
        return
```
---
## How to test

In order to activate Vault usage (+ kub8s auth method) on any service do following: in corresponding `values.yaml` set  `vault.addr` as vault address, `vault.role` to  service role (in spinless it's being defined as `"{}-role".format(self.app_path)`) and `vault.jwtprovider` to kub8s cluster name. 

---
## References:
https://learn.hashicorp.com/vault/getting-started-k8s/external-vault
https://www.vaultproject.io/docs/platform/k8s/helm/examples/external
https://www.vaultproject.io/api/auth/kubernetes#login
https://www.vaultproject.io/api/auth/kubernetes#create-role
https://www.vaultproject.io/api/auth/jwt#jwt-login
https://www.vaultproject.io/api/auth/jwt#create-role

**Comment by snripa** [comment]
fixed

**Comment by artem-v** [comment]
reopening because of bugs

**Comment by snripa** [comment]
fixed

**Comment by snripa** [comment]
issues fixed and cloud creation is automated
