### ISSUE TITLE
Provision oidc token generation mini-infra for service provider

### ISSUE THREAD

**Issue by artem-v** [scalecube/spinless#36]
## Motivation

As part of m2m auth every service must be treated as potential service provider, hence spinless must account for _roles_ (array)  from helm chart values. Base on that  there must be built upfront  certain infra for oidc token generation. See [this link](https://www.vaultproject.io/docs/secrets/identity) for Vault Identity secrets engine.

## Subtasks

- [ ] ServiceProvider / provision oidc token generation mini-infra: **role**.

### role: oidc/role is a place where to declare template with custom claims for future generated jwt identity token.

Function: `createIdentityRole(:role, :key, :ttl, :template)`

Example:
```
// with optional ttl set to 1h
createIdentityRole("operations", "exberry-io-exchange-operation-gateway", "1h", {"permissions":"operations"}`)
```
```
// without optaional ttl, by default shall be set to 1m
createIdentityRole("access-keys", "exberry-io-exchange-auth-service", {"permissions":"access-keys"}`)
```

Inputs:
 * `role` -- comes from helm chart values file.
 * `key` -- comes as `$owner-$repo` (it's a single key per service).
 * `ttl` -- optional (by default 1 minute), resulted jwt token exp time.
 * `template` -- comes from helm chart values file.

Vault command:
```
# Create oidc/role
echo "{\"key\": \"$key\", "ttl": \"$ttl\", \"template\": \"$template\"}" > payload.json
curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data @payload.json $VAULT_ADDR/v1/identity/oidc/role/$role
```

---
- [ ] ServiceProvider / provision oidc token generation mini-infra: **key**.
### key: oidc/id key bound for each service.

Function: `createIdentityKey(:owner, :repo, :verification_ttl, rotation_period)`

Example:
```
In examples below `verification_ttl` wasn't set, by default shall be set to 1h, same applies to `rotation_period`.
createIdentityKey("exberry-io-exchange-operation-gateway")
createIdentityKey("exberry-io-exchange-auth-service")
```

Inputs: pretty clear.

Vault command:
```
# Create oidc/key
echo "{\"allowed_client_ids\": \"*\", \"verification_ttl\": \"1h\", \"rotation_period\": \"1h\"}" > payload.json
curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST --data @payload.json $VAULT_ADDR/v1/identity/oidc/key/$owner-$repo
```

---
- [ ] ServiceProvider / provision oidc token generation mini-infra: **token policy**.
### oidc token policy: policy for path identity/oidc/token/:role

Function: `createIdentityTokenPolicy(:role)`

Example: 
`createIdentityTokenPolicy("operations")` 
`createIdentityTokenPolicy("access-keys")`

Inputs:
 * `role` -- comes from helm chart values file.

Vault command:
```
# Register policy which allows to generate oidc token
curl -X PUT -H "X-Vault-Token: $VAULT_TOKEN" -d '{"policy":"path \"identity/oidc/token/$role\" {capabilities=[\"read\"]}"}' $VAULT_ADDR/v1/sys/policies/acl/$role-oidc-token-policy

```

**Comment by artem-v** [comment]
We dropping this. It will in java.
